### ISSUE TITLE
ModTek.log Warnings

### ISSUE THREAD

**Issue by OrnoCav** [shaygover/BTshopsupgrade#2]
While taking this mod for a test drive, I was looking at the logs and found several entries stating
`Warning: Could not find an existing VersionManifest entry for...
`

Weapon_Gauss_Gauss_2-SCI!
Weapon_Laser_LargeLaserER_3-SCI!
Weapon_Laser_LargeLaserPulse_3-SCI!
Weapon_Laser_MediumLaserER_3-SCI!
Weapon_Laser_MediumLaserPulse_3-SCI!
Weapon_Laser_SmallLaserER_3-SCI!
Weapon_Laser_SmallLaserPulse_3-SCI!
Weapon_PPC_PPCER_2-Kong!

are these a WiP or is there something missing?

**Comment by shaygover** [comment]
I see those too. But they work fine. As far as I understand, the manifest is for item that can be mounted by the enemy
