### ISSUE TITLE
Mods enabled, but items not showing up in store

### ISSUE THREAD

**Issue by CRPOV** [shaygover/BTshopsupgrade#3]
So even though I created their own folders, neither this or any of your other mods (Heat and Weight, Streak missiles & Royal mechs in shops) are working for me. I've just completed the Weldry mission, but none of the items are in the Arano shop. I travelled to Fjaldr to see if it was a quirk. Still nothing. Any idea what's wrong? I have the latest version of these mods & ModTek.

**Comment by shaygover** [comment]
It should look like this in the file explorer:
[image: image.png]

Folder name doesn't matter.
Did you install modtek and it's injector?

Please attach ModTek.log

**Comment by shaygover** [comment]
Also make sure you used the last version

**Comment by CRPOV** [comment]
Here's the ModTek.log - I couldn't see anything odd: 
[ModTek.log](https://github.com/shaygover/BTshopsupgrade/files/4704148/ModTek.log)

Also, what do you mean "It should look like this in the file explorer?"

**Comment by shaygover** [comment]
Log looks good. Try 0.5.7.

**Comment by shaygover** [comment]
Also, Note that WeaponDiversity seems to replace some of the lists I'm using. No idea what it'll do.

**Comment by CRPOV** [comment]
I think that it - that Weapon Diversity is overwriting this one.

**Comment by CRPOV** [comment]
0.5.7 of what mod? I've got all the latest of yours, the ones you put up on the 24th

**Comment by shaygover** [comment]
this one. I also updated HM.

**Comment by CRPOV** [comment]
Unfortunately it still doesn't work; I'm betting it's that conflict. Thanks for all the help though.

**Comment by shaygover** [comment]
Will add that to the readme.
Closing.
